GET http://localhost:3000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NjYxOTY0ODksImV4cCI6MTY3NDgzNjQ4OSwiYXVkIjoiNjM1MDI0MDU5M2NhY2Q2ZjBhOTdkMjcxIiwiaXNzIjoicGlja3VycGFnZS5jb20ifQ.9_VxX9PLuiyfDMk5mroswf2iDBjKCWW4WhqgWXhgyr8


###
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "manishkrsingh2645@gmail.com",
    "password": "manish"
}

### register routes
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "name": "Manish Kumar Singh",
    "email": "manishkrsingh2645@gmail.com",
    "password": "manish"
}

###
POST http://localhost:3000/auth/refresh-token

###
DELETE  http://localhost:3000/auth/logout